name: 'Build Debian package: Buster'
description: 'Build a Debian package, using the latest version of Debian Buster'

runs:
  using: docker
  image: Dockerfile

branding:
  icon: package
  color: gray-dark
