name: 'Build Debian package: Bullseye'
description: 'Build a Debian package, using the latest version of Debian Bullseye'

runs:
  using: docker
  image: Dockerfile

branding:
  icon: package
  color: gray-dark
